version: "3.8"

services:
  free5gc-upf:
    container_name: "upf"
    image: oaisoftwarealliance/oai-upf:develop
    expose:
        - 2152/udp
        - 8805/udp
        - 8080/tcp
    volumes:
        - ./conf/oai_upf_config.yaml:/openair-upf/etc/config.yaml
        - /sys/fs/bpf:/sys/fs/bpf
        - /sys/kernel/debug:/sys/kernel/debug:rw
    environment:
        - TZ=Europe/Paris
    depends_on:
        - free5gc-nrf
    cap_add:
        - NET_ADMIN
        - SYS_ADMIN
    cap_drop:
        - ALL
    privileged: true
    network_mode: host
    extra_hosts:
        - "oai-ext-dn:10.100.150.135"
        - "oai-nrf:10.100.200.139"

  db:
    container_name: mongodb
    image: mongo:4.4
    command: mongod --port 27017
    expose:
      - "27017"
    volumes:
      # - dbdata:/data/db
      - './db/dump:/data/dump'
      - './db/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh'
    networks:
      privnet:
        aliases:
          - db

  free5gc-nrf:
    container_name: nrf
    image: free5gc/nrf:v4.1.0
    command: ./nrf -c ./config/nrfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/nrfcfg.yaml:/free5gc/config/nrfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - nrf.free5gc.org
        ipv4_address: 10.100.200.139
    depends_on:
      - db

  free5gc-amf:
    container_name: amf
    image: free5gc/amf:v4.1.0
    command: ./amf -c ./config/amfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/amfcfg.yaml:/free5gc/config/amfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        # ipv4_address: 10.100.200.132
        aliases:
          - amf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-ausf:
    container_name: ausf
    image: free5gc/ausf:v4.1.0
    command: ./ausf -c ./config/ausfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/ausfcfg.yaml:/free5gc/config/ausfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - ausf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-nssf:
    container_name: nssf
    image: free5gc/nssf:v4.1.0
    command: ./nssf -c ./config/nssfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/nssfcfg.yaml:/free5gc/config/nssfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - nssf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-pcf:
    container_name: pcf
    image: free5gc/pcf:v4.1.0
    command: ./pcf -c ./config/pcfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/pcfcfg.yaml:/free5gc/config/pcfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - pcf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-smf:
    container_name: smf
    image: free5gc/smf:v4.1.0
    command: ./smf -c ./config/smfcfg.yaml -u ./config/uerouting.yaml
    expose:
      - "8000"
    volumes:
      - ./config/smfcfg.yaml:/free5gc/config/smfcfg.yaml
      - ./config/uerouting.yaml:/free5gc/config/uerouting.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - smf.free5gc.org
    depends_on:
      - free5gc-nrf
      - free5gc-upf

  free5gc-udm:
    container_name: udm
    image: free5gc/udm:v4.1.0
    command: ./udm -c ./config/udmcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/udmcfg.yaml:/free5gc/config/udmcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - udm.free5gc.org
    depends_on:
      - db
      - free5gc-nrf

  free5gc-udr:
    container_name: udr
    image: free5gc/udr:v4.1.0
    command: ./udr -c ./config/udrcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/udrcfg.yaml:/free5gc/config/udrcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - udr.free5gc.org
    depends_on:
      - db
      - free5gc-nrf

  free5gc-chf:
    container_name: chf
    image: free5gc/chf:v4.1.0
    command: ./chf -c ./config/chfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/chfcfg.yaml:/free5gc/config/chfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - chf.free5gc.org
    depends_on:
      - db
      - free5gc-nrf
      - free5gc-webui

  free5gc-nef:
    container_name: nef
    image: free5gc/nef:v4.1.0
    command: ./nef -c ./config/nefcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/nefcfg.yaml:/free5gc/config/nefcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - nef.free5gc.org
    depends_on:
      - db
      - free5gc-nrf

  free5gc-webui:
    container_name: webui
    image: free5gc/webui:v4.1.0
    command: ./webui -c ./config/webuicfg.yaml
    expose:
      - "2121"
    volumes:
      - ./config/webuicfg.yaml:/free5gc/config/webuicfg.yaml
    environment:
      - GIN_MODE=release
    networks:
      privnet:
        ipv4_address: 10.100.200.141
        aliases:
          - webui
    ports:
      - "5000:5000"
      - "2122:2122"
      - "2121:2121"
    depends_on:
      - db
      - free5gc-nrf
  oai-ext-dn:
    privileged: true
    init: true
    container_name: oai-ext-dn
    image: oaisoftwarealliance/trf-gen-cn5g:latest
    environment:
      - EBPF_GW_SETUP=yes
      - EBPF_GW_N6_IP_ADDR=10.100.150.135
      - GW_SGI_IP_ADDR=192.168.70.135
      - GW_N3_IP_ADDR=10.100.100.135
      - UE_IP_ADDRESS_POOL=12.1.1.0/24
      - N6_UPF_IP_ADDR=110.100.150.129
      - SGI_DEMO_OAI_ADDR=192.168.70.129
    healthcheck:
      test: /bin/bash -c "ip r | grep 12.1.1"
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      privnet:
        # ipv4_address: 10.100.200.135
      n3_net:
        # ipv4_address: 10.100.100.135
      n6_net:
        # ipv4_address: 10.100.150.135
  gnb:
    cap_add:
      - NET_ADMIN
    command: ./nr-gnb -c /ueransim/config/gnbcfg.yaml
    container_name: gnb
    depends_on:
      - free5gc-amf
      - free5gc-upf
    devices:
      - /dev/net/tun
    image: 'tariromukute/ueransim:v3.2.7'
    networks:
      privnet:
        aliases:
          - gnb.free5gc.org
    volumes:
      - './ueransim/free5gc-gnb.yaml:/ueransim/config/gnbcfg.yaml'
      - './ueransim/free5gc-ue.yaml:/ueransim/config/uecfg.yaml'

  ue:
    cap_add:
      - NET_ADMIN
    command:
      - /bin/bash
      - '-c'
      - |
        sleep 15
        echo "Starting UE..."
        nr-ue -c /ueransim/config/uecfg.yaml
        tail -f /dev/null
    container_name: ue
    depends_on:
      - free5gc-amf
      - free5gc-upf
    devices:
      - /dev/net/tun
    image: 'tariromukute/ueransim:v3.2.7'
    networks:
      privnet:
        aliases:
          - ue.free5gc.org
    volumes:
      - './ueransim/free5gc-gnb.yaml:/ueransim/config/gnbcfg.yaml'
      - './ueransim/free5gc-ue.yaml:/ueransim/config/uecfg.yaml'

networks:
  privnet:
    ipam:
      driver: default
      config:
        - subnet: 10.100.200.128/26
    driver_opts:
      com.docker.network.bridge.name: br-free5gc

  n3_net:
    driver: bridge
    name: demo-oai-n3-net
    ipam:
        config:
            - subnet: 10.100.100.128/26
    driver_opts:
        com.docker.network.bridge.name: "demo-n3"
  n6_net:
    driver: bridge
    name: demo-oai-n6-net
    ipam:
        config:
            - subnet: 10.100.150.128/26
    driver_opts:
        com.docker.network.bridge.name: "demo-n6"


volumes:
  dbdata:
